env:
  - CABALVER=3.0 GHCVER=7.8.4 SODIUMVER=1.0.13
  - CABALVER=3.0 GHCVER=7.10.3 SODIUMVER=1.0.13
  - CABALVER=3.0 GHCVER=8.0.2 SODIUMVER=1.0.13
  - CABALVER=3.0 GHCVER=8.2.2 SODIUMVER=1.0.13
  - CABALVER=3.0 GHCVER=8.4.4 SODIUMVER=1.0.13
  - CABALVER=3.0 GHCVER=8.6.5 SODIUMVER=1.0.13
  - CABALVER=3.0 GHCVER=8.8.3 SODIUMVER=1.0.13

matrix:
  fast_finish: true

before_install:
  - curl -# -L https://github.com/jedisct1/libsodium/releases/download/$SODIUMVER/libsodium-$SODIUMVER.tar.gz | tar xzf -
  - (cd libsodium-$SODIUMVER && ./autogen.sh && ./configure && make check && sudo make install && sudo ldconfig)
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
  - export LIBRARY_PATH=/usr/local/lib:$LIBRARY_PATH
  - export C_INCLUDE_PATH=/usr/local/include:$C_INCLUDE_PATH
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.cabal/bin:$PATH

install: true

script: ./travis.sh

notifications:
  email: true
