env:
  - CABALVER=1.16 GHCVER=7.6.3 SODIUMVER=1.0.2
  - CABALVER=1.18 GHCVER=7.8.4 SODIUMVER=1.0.2
  - CABALVER=1.22 GHCVER=7.10.1 SODIUMVER=1.0.2

matrix:
  fast_finish: true
  allow_failures:
  - env: CABALVER=1.16 GHCVER=7.6.3 SODIUMVER=1.0.2
  - env: CABALVER=1.22 GHCVER=7.10.1 SODIUMVER=1.0.2

before_install:
  - curl -# -L https://github.com/jedisct1/libsodium/releases/download/$SODIUMVER/libsodium-$SODIUMVER.tar.gz | tar xzf -
  - (cd libsodium-$SODIUMVER && ./autogen.sh && ./configure && make check && sudo make install && sudo ldconfig)
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.cabal/bin:$PATH

install:
  - travis_retry cabal update
  - cabal install --only-dependencies --enable-tests --enable-benchmarks

script:
  - cabal configure --enable-tests --enable-benchmarks -v2

  - cabal build
  - cabal haddock
  - cabal test --show-details=always

  - cabal check
  - cabal sdist && cabal install --force-reinstalls dist/saltine-*.tar.gz

notifications:
  email: true
